### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by adriel-mp3** [adriel-mp3/portifolio#11]
## Tasks

- [x] User can navigate between slides by clicking and dragging
- [x] All functions are perfectly usable on mobile devices
- [x] Slide adjusts according to the screen size
- [x] Activate the first item upon entering the page
- [x] Create a debounce function to improve slide performance
- [x] Define in script.js how the slide will behave
- [x] Add arrows to facilitate navigation
