### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by adriel-mp3** [adriel-mp3/portifolio#17]
## Tasks

- [ ] Verify the main breakpoints where font-size needs to be adjusted
- [ ] Modify sizes and add breakpoints in the font.css file
- [ ] Adjust line-height based on font-size
