### ISSUE TITLE
Decoration

### ISSUE THREAD

**Issue by adriel-mp3** [adriel-mp3/portifolio#18]
## Tasks

- [ ] Adjust size of each decorative svg
- [ ] Verify if it's still worth keeping the svg or not
- [ ] Adjust slide buttons
- [ ] Break icons into a grid to prevent them from being squished
